const jdList = [
  {
    name: "Field Application Engineer",
    tag: "全职",
    type: "电子技术类",
    com: "一家全球电量传感器的知名企业",
    address: "深圳、上海",
    time: "2024/5/17",
    conf: {
      jd1: [
        "1.负责行业细分领域的现场应用知识，作为销售和客户的第一级技术接口，根据客户的需求(现有产品或新开发)定义和推广最合适的解决方案。",
        "2.参与公司的新产品开发，获取应用信息，支持新产品的设计和客户应用验证。",
        "3.储存、交流和应用培训和经验教训，负责对销售机构/客户/经销商进行基础和应用培训。",
      ],
      jd2: [
        "1.5年以上电力电子行业工作经验",
        "2.大学学历，电子/机电一体化专业",
        "3.英语沟通流利",
      ],
    },
  },
  {
    name: "National Personal Safety Sales Manager",
    tag: "全职",
    type: "销售类",
    com: "One of the world's leadingmanufacturers of filters and components",
    address: "苏州",
    time: "2024/5/17",
    conf: {
      jd1: [
        "1.Identifying new customers for products",
        "2.Scheduling and attending meetings and phone and e-mail follow-up with customers to keep pace with all customer product development or engineering activities that could lead to product opportunities ",
        "3.Collecting pertinent market data/information to be used in accurate sales forecasting",
        "4.Responsible for the sales numbers for his/her own product line",
      ],
      jd2: [
        "1.5+ years working experience in selling industrial products through distributors: ideal candidate has previous working experience in PPE European/international company, working experience in Facemask business is not a must but a plus;",
        "2.Good selling skills and selling channels,having distributors management experience,excellent communication skill,hard working and able to travel frequently;",
        "3.Good verbal and written English communication skills;",
      ],
    },
  },
  {
    name: "Paralegal-APAC",
    tag: "全职",
    type: "法律类",
    com: "A world leader in mineral-based specialties",
    address: "上海",
    time: "2024/5/17",
    conf: {
      jd1: [
        "1.Provide corporate governance related support with full spectrum of corporate secretarial duties, including approval workflow, document preparation, registration & filing, record &corporate calendar maintenance, compliance with relevant statutory and regulatory requirements, etc.;",
        "2.Carry out compliance check per  compliance related policies, including intermediary check, international sanction check, etc.;",
        "3.Facilitate approval and signing process of contracts and other documents, including name list check under approval matrix, signature collection, etc.;",
      ],
      jd2: [
        "1.Education background in law (bachelors’ degree in law - preferred);",
        "2.Minimum 3 years of full-time professional experience as in-house paralegal (company covering APAC is preferred) or law firm experience;",
        "3.Fluent in both written and spoken English;",
      ],
    },
  },
  {
    name: "BD Manager",
    tag: "全职",
    type: "销售类",
    com: "一家为全球客户提供精密的医疗、通信、消费、工业类塑料件的外企",
    address: "苏州",
    time: "2024/5/17",
    conf: {
      jd1: [
        "1.根据KPI确定客户发展目标，聚焦于医疗、汽车、电子等行业。",
        "2.细分市场预算，包括成本控制。",
        "3.计算的准确性和报价。",
        "4.实现销售并移交给客服团队。",
      ],
      jd2: [
        "1.超过2年的塑料注塑件技术销售商业经验。",
        "2.具有业务发展思维，能够通过为关键客户业务问题提供最佳解决方案来识别商机和增长领域。",
        "3.以短期结果为导向，具有竞争力，是一个精力充沛的自我驱动者，推动行动计划并跟进完成。",
        "4.有一定的英语书面能力，口语可简单沟通即可。",
      ],
    },
  },
  {
    name: "Customer Service Specialist",
    tag: "全职",
    type: "客户服务类",
    com: "一家为全球各行业的客户提供精密的塑料零部件的外资企业",
    address: "苏州",
    time: "2024/5/17",
    conf: {
      jd1: ["1.处理订单交付阶段的客服工作"],
      jd2: [
        "1.英语口语流利",
        "2.有医疗/汽车/电子行业工作经验，或有上述行业较丰富的客户服务经验",
      ],
    },
  },
  {
    name: "销售总监",
    tag: "全职",
    type: "销售类",
    com: "全球知名的大型包装设备及整线解决方案供应商之一",
    address: "上海、江苏、浙江",
    time: "2024/5/17",
    conf: {
      jd1: [
        "1.高层管理职位，协助决策层制定公司发展战略，负责其功能领域内短期及长期的公司决策和战略，对公司中长期目标的达成产生重要影响。",
        "2.负责公司的业务拓展、销售运作，能强有力的将计划转变成结果",
        "3.建立和管理销售队伍，规范销售流程，完成销售目标，关注于维护和提高公司市场竞争力。",
        "4.设置销售目标、销售模式、销售战略、销售预算和奖励计划。",
      ],
      jd2: [
        "1.在大型机械设备行业有丰富的管理经验。",
        "2.出色的领导和团队管理能力，有敏锐的市场意识、应变能力、领导能力和独立开拓市场的能力，学习能力强;逻辑性强和良好的语言表达能力。",
        "3.流利英文，有外企背景，曾经汇报给欧美老板背景优先。",
      ],
    },
  },
  {
    name: "电商设计师",
    tag: "全职",
    type: "互联网类",
    com: "空调行业龙头企业",
    address: "苏州",
    time: "2024/5/17",
    conf: {
      jd1: [
        "1.抖音内容拍摄：根据策划需求，进行抖音短视频素材的拍摄收集、整理和剪辑，确保视频质量和效果；",
        "2.直播间设计及布置：包括视觉主题设计、氛围营造、效果优化等。",
        "3.抖音直播后期制作：负责直播内容的后期制作，包括视频剪辑、特效添加和音频处理等。",
        "4.电商店铺（抖音小店或天猫）把控电商店铺页面整体风格和视觉呈现，全面提升电商产品页面品牌形象和视觉效果；",
        "5.负责店铺首页、详情页、主图、活动页面的设计制作、修改和优化；",
        "6.跟进站内产品推广所需海报、单页、banner、广告图的设计；",
        "7.根据店铺运营数据反馈，定期优化店铺主页、配合活动制定相关营销设计策略，对店铺整体设计输出、设计效果（图片点击率、转化率）负责；",
        "8.挖掘消费者的浏览习惯及点击需求，进行设计前期调研分析；",
      ],
      jd2: [
        "1.美术或广告设计相关大专及以上学历；",
        "2.具备优秀的视频拍摄及剪辑技能，熟练使用专业视频剪辑软件。具备2年以上短视频及直播后期拍摄剪辑经验；",
        "3.熟悉电商网店，1年以上电商店铺设计经验，能独立完成全店风格把控及营销活动设计；有工业品设计经验优先；",
        "4.有良好的美术功底和美工基础，具备视觉表现、版式规划、色彩搭配等设计能力，有一定的运营思维；",
      ],
    },
  },
  {
    name: "销售工程师",
    tag: "全职",
    type: "销售类",
    com: "空调行业龙头企业",
    address: "宁波、杭州",
    time: "2024/4/8",
    conf: {
      jd1: [
        "1.负责公司营销策略、政策和计划的实施和落地；",
        "2.负责销售指标的落地和跟踪；",
        "3.负责区域内渠道开发、管理，并协助渠道进行销售运营、市场开拓",
        "4.负责区域内项目的跟踪和管理，并协助渠道进行项目攻关",
        "5.负责区域内渠道的管理和评价",
        "6.协助销售经理进行市场需求信息的调研、收集、分析和反馈",
        '7.可进行招投标项目文件的准备、产品选型"',
      ],
      jd2: [
        "1.专科以上学历，理工科背景，空调、暖通相关专业背景优先；",
        "2.5 年以上暖通类或机电类服务销售工作经验；",
        "3.熟悉多联机、水机安装和应用，有大型项目或渠道经验优先",
        "4.能把握市场需求和动向，具备独立开发市场的能力",
        "5.具备渠道开发和运营能力，有经销商运营经验优先",
      ],
    },
  },
  {
    name: "Sales Manager/Engineer",
    tag: "全职",
    type: "销售类",
    com: "一家行业内知名的德国公司",
    address: "广州、深圳",
    time: "2024/4/8",
    conf: {
      jd1: [
        "1.关键客户管理：实现收入、业务发展和利润率目标",
        "2.项目搜寻，包括客户、承包商、设计院等，能够提供专业支持达成合作",
        "3.技术销售：能够为客户提供产品解决方案，独立组织产品介绍，通过解决问题建立信任。",
      ],
      jd2: [
        "1.4 年+建筑/工业项目销售相关经验，建筑、土木工程、机械/工业工程学士或同等学历者优先。有项目管理经验优先。",
        "2.有客户关系管理系统的经验。",
        "3.流利的英语口语和写作为加分项",
      ],
    },
  },
  {
    name: "Regional Sales Manager",
    tag: "全职",
    type: "销售类",
    com: "全球知名的大型包装设备及整线解决方案供应商之一",
    address: "深圳 香港",
    time: "2024/4/8",
    conf: {
      jd1: [
        "1.完成公司制定的销售目标。",
        "2.建立有效的项目信息获取渠道，识别和开发新的市场机会。",
        "3.与现有客户保持有效沟通和良好客情关系，进行深度二次开发。",
      ],
      jd2: [
        "1.三年以上工业品成功销售经验，有⾷品包装机械、自动化整线、包装材料、或解决方案类销售背景更佳。擅长高附加值产品和解决方案类产品的销售",
        "2.敏锐的市场意识，能敏锐地捕捉市场机会点、深度分析客户需求和竞争态势，并据此制定解决方案和竞争策略的能力。",
        "3.优秀的客户关系处理能力，能熟练处理好与客户各层级的关系，包括具备与客户中层进行深度业务沟通和跟客户高层展开业务对话的能力。",
      ],
    },
  },
  {
    name: "人事专员",
    tag: "全职",
    type: "人事类",
    com: "一家知名的化工公司",
    address: "金山化工园区",
    time: "2024/4/8",
    conf: {
      jd1: [
        "1.主要执行、实施员工的聘用、培训等人力资源管理工作，兼顾薪酬和员工关系的相关工作。",
        "2.负责办理员工入职、离职、异动等相关人事手续，特别是协调各部门职能安排入职培训。",
        "3.执行公司人力资源的各类规章制度的实施。",
        "4.负责管理人力资源相关文件和档案，以及完成上级交给的其它事务性工作。",
      ],
      jd2: [
        "1.本科及以上学历，人力资源专业优先。",
        "2.具有3-5年人力资源工作经验，服务过100人以上工厂经验，熟悉工人的考核；有招聘和培训经验优先，有薪酬、绩效、员工关系经验是加分项。",
        "3.英语读写能力。",
        "4.熟悉使用MS Office。",
      ],
    },
  },
  {
    name: "Wind Power Generation Sales Manager",
    tag: "全职",
    type: "销售类",
    com: "A well-known foreign company",
    address: "China",
    time: "2024/4/8",
    conf: {
      jd1: [
        "1.Developing and maintaining relationships with clients",
        "2.Identifying customer needs and providing effective solutions using hydraulic components",
        "3.Requires a strong understanding of the wind power industry and expertise in hydraulics",
        "4.Access, ability and knowledge to specify our products for the application in WPG",
      ],
      jd2: [
        "1.Expertise in hydraulic components (hydraulic filters would be desirable)",
        "2.Background in wind power generation is essential",
        "3.Speaks English",
      ],
    },
  },
  {
    name: "区域销售经理",
    tag: "全职",
    type: "销售类",
    com: "一家德国奢侈品灯具品牌",
    address: "上海",
    time: "2024/4/8",
    conf: {
      jd1: [
        "1.通过对经销商门店的日常销售数据等的运营管理，协助经销商搭建健康的门店运营体系，完成公司制定的区域的年度、月度销售计划。",
        "2.经销商门店的统筹规范，对经销商门店不断进行检查与培训（例如：销售技巧、陈列、店面形象等），定期走访市场各门店，发现问题并及时制定解决方案。",
        "3.负责对公司的政策、制度、策略、终端活动方案落实，市场氛围营造。",
        "4.协助完成经销商新门店建店过程中的对接及沟通。",
      ],
      jd2: [
        "1.本科及以上学历，3 年以上奢侈品行业或是进口家居工作经验者优先。",
        "2.熟悉经销商运营管理，具备相应的店铺营运管理能力。",
        "3.英语可作为工作语言。",
      ],
    },
  },
  {
    name: "KA Manager",
    tag: "全职",
    type: "销售类",
    com: "一家全球知名的电量传感器公司",
    address: "深圳",
    time: "2024/4/8",
    conf: {
      jd1: [
        "1.负责汽车行业大客户，实现收入、业务发展和利润率目标。",
        "2.了解所负责市场领域的市场/客户情况和竞争对手的情况。识别关键客户，管理关键客户，实现公司战略目标。",
        "3.能够为客户提供产品解决方案，独立组织产品介绍，通过解决问题建立信任。",
        "4.月度、季度和年度业务收入计划，保持预测，BDG计划，业务分析，战斗计划和专业的数据逻辑报告。",
      ],
      jd2: [
        "1.5年以上汽车行业相关销售和大客户管理经验，有新能源汽车、电机控制和BMS系统方面的经验者优先。",
        "2.熟练的办公软件，如Excel，PowerPoint是一个必须的。",
        "3.流利的英语口语和写作。",
        "4.愿意经常在中国境内出差（最多50%的时间）。",
      ],
    },
  },
  {
    name: "WCM & Lean Champion",
    tag: "全职",
    type: "生产制造类",
    com: "一家从事滤清器外资集团公司",
    address: "上海",
    time: "2024/4/8",
    conf: {
      jd1: [
        "1.系统地争取制造改进的机会，承担责任工艺改进，如提高KAIZEN、提高效率、减少损耗等。",
        "2.协调整个工厂的精益方法和工具",
        "3.协助工厂经理/运营部门规划和组织精益实施过程",
      ],
      jd2: [
        "1.熟练掌握精益制造、能力研究、问题解决、线平衡和价值流研究",
        "2.有汽车生产、装配和合资公司经验者优先",
        "3.有六西格玛黑带、绿带优先",
        "4.英文可以作为工作语言",
      ],
    },
  },
];
export { jdList };
